AllocateMemmory MACRO
	PUSH RCX 
	PUSH RDX
	ADD RSP, 20h
	MOV RCX, 5
	CALL malloc
	SUB RSP, 20h
	POP RDX
	POP RCX
ENDM

.DATA
EXTRN malloc : PROC
EXTRN free : PROC
income_margin DQ 200
gpa_margin DD 0.5

.CODE

DetectBelowAverageUsers PROC		;RCX - GPAS, RDX - INCOMES, R8 - ACTIVITY, R9 - NUMBER OF PERSONS
	PUSH RBX 
	
	CMP R9, 0
	JE _TRAVERSED

	;SAVE OG SIZE AND GET NEW ONE (TIMES 4)
	PUSH R9
	PUSH RDX
	MOV RAX, R9
	MOV RDX, 4
	IMUL RDX
	MOV R9, RAX
	POP RDX

	;AllocateMemmory
	PUSH RCX 
	PUSH RDX
	PUSH R8
	PUSH R9
	SUB RSP, 20h
	MOV RCX, 40						;5*8=20
	CALL malloc
	ADD RSP, 20h
	POP R9
	POP R8
	POP RDX
	POP RCX

	PUSH RAX

	;FIND GPAA
	XOR RSI, RSI
	XORPS XMM0, XMM0
	_FOR1:
		MOVSS XMM1, DWORD PTR [RCX+RSI]
		ADDSS XMM0, XMM1
		ADD RSI, 4
		CMP RSI, R9
		JL _FOR1

	;RELOAD THE OG SIZE
	POP RAX
	POP RSI
	PUSH RAX
	PUSH RSI

	CVTSI2SS XMM1, RSI
	DIVSS XMM0, XMM1				;XMM0 - GPAA

	;FIND INCOME AVERAGE
	XOR RSI, RSI
	XORPS XMM1, XMM1
	_FOR2:
		MOVSS XMM2, DWORD PTR [RDX+RSI]
		ADDSS XMM1, XMM2
		ADD RSI, 4
		CMP RSI, R9
		JL _FOR2

	POP RSI
	CVTSI2SS XMM2, RSI
	DIVSS XMM1, XMM2				;XMM1 - INCOME AVERAGE

	;THE WHOLE "FIRST" 5 GUYS BELOW AVERAGE PART
	XOR RSI, RSI
	XOR RDI, RDI
	XOR RBX, RBX
	POP RAX
	_FOR3:
		CMP RSI, R9
		JGE _TRAVERSED

		PUSH RDX
		PUSH RSI
		ADD RSI, RSI
		MOV RDX, [R8+RSI]
		POP RSI
		MOVSS XMM4, DWORD PTR [R8 + RDX]
		POP RDX 

		MOVSS XMM3, DWORD PTR [gpa_margin]
		MULSS XMM3, XMM4

		MOVSS XMM2, DWORD PTR [RCX+RSI]
		ADDSS XMM2, XMM3				;THE PARTICIPATION ROLE
		UCOMISS XMM2, XMM0
		JB _RECORD_THE_GUY

		PUSH RDX
		PUSH RSI
		ADD RSI, RSI
		MOV RDX, [R8+RSI]
		POP RSI
		MOVSS XMM4, DWORD PTR [R8 + RDX]
		POP RDX 

		MOVSS XMM3, DWORD PTR [income_margin]
		MULSS XMM3, XMM4

		MOVSS XMM2, DWORD PTR [RDX+RSI]
		ADDSS XMM2, XMM3				;THE PARTICIPATION ROLE
		UCOMISS XMM2, XMM1
		JB _RECORD_THE_GUY

		ADD RSI, 4
		INC RBX
		JMP _FOR3
	
	_RECORD_THE_GUY:
		MOV [RAX+RDI], RBX
		ADD RDI, 8
		ADD RSI, 4
		INC RBX
		JMP _FOR3

	_TRAVERSED:
		POP RBX
		RET						;SHOULD RETURN 5 INDECES OF THE TARGETS

DetectBelowAverageUsers ENDP

FreeMemory PROC
	PUSH RBX

	SUB RSP, 32
	CALL free
	ADD RSP, 32

	POP RBX
	RET
FreeMemory ENDP

END
